server:
  port: 8080


#指定注册中心地址
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/

#服务的名称
spring:
  application:
    name: common-service